import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface ReportData {
  companyName: string;
  totalUnits: number;
  peakPenalties: number;
  actionPlan: string[];
}

export const generateReport = (data: ReportData) => {
  const doc = new jsPDF();

  /* ================= HEADER ================= */
  doc.setFontSize(22);
  doc.setTextColor(249, 115, 22);
  doc.text("Kovai MSME-Optima", 14, 20);

  doc.setFontSize(14);
  doc.setTextColor(100);
  doc.text("Monthly Energy Intelligence Report", 14, 28);

  doc.setFontSize(10);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 34);
  doc.text(`Company: ${data.companyName}`, 14, 39);

  /* ================= METRICS ================= */
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text("Performance Metrics / செயல்திறன் அளவீடுகள்", 14, 50);

  autoTable(doc, {
    startY: 55,
    head: [["Metric / அளவுரு", "Value / மதிப்பு"]],
    body: [
      ["Total Consumption / மொத்த பயன்பாடு", `${data.totalUnits} Units`],
      [
        "Peak Hour Penalty / உச்ச நேர அபராதம்",
        `₹${data.peakPenalties.toLocaleString()}`,
      ],
      [
        "Efficiency Score / செயல்திறன் மதிப்பீடு",
        "B+ (Improving / மேம்படுகிறது)",
      ],
    ],
    theme: "grid",
    headStyles: { fillColor: [249, 115, 22] },
    styles: {
      fontSize: 10,
      cellPadding: 3,
      font: "helvetica",
    },
  });

  /* ================= TREND ANALYSIS ================= */
  const comparisonY = (doc as any).lastAutoTable.finalY + 15;

  doc.setFontSize(14);
  doc.text("Trend Analysis / போக்கு பகுப்பாய்வு", 14, comparisonY);

  autoTable(doc, {
    startY: comparisonY + 5,
    head: [["Period", "Consumption", "Trend"]],
    body: [
      ["Current Month", `${data.totalUnits} Units`, "-"],
      [
        "Previous Month",
        `${Math.round(data.totalUnits * 0.9)} Units`,
        "+10% Increase",
      ],
      [
        "Industrial Avg",
        "10,000 Units",
        data.totalUnits > 10000 ? "High" : "Low",
      ],
    ],
    theme: "striped",
    headStyles: { fillColor: [59, 130, 246] },
    styles: { fontSize: 10 },
  });

  /* ================= AI STRATEGY ================= */
  const finalY = (doc as any).lastAutoTable.finalY + 15;

  doc.setFontSize(14);
  doc.text("AI Strategy / AI உத்தி", 14, finalY);

  const actionRows = data.actionPlan.map((plan, index) => [
    `#${index + 1}`,
    plan,
  ]);

  autoTable(doc, {
    startY: finalY + 5,
    head: [["Priority / முன்னுரிமை", "Recommendation / பரிந்துரை"]],
    body: actionRows,
    theme: "striped",
    headStyles: { fillColor: [34, 197, 94] },
    columnStyles: {
      0: { cellWidth: 25, fontStyle: "bold" },
      1: { cellWidth: "auto" },
    },
  });

  /* ================= FOOTER ================= */
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text(
    "Generated by Kovai MSME-Optima Platform",
    14,
    pageHeight - 10
  );

  doc.save(`Energy_Report_${data.companyName.replace(/\s+/g, "_")}.pdf`);
};
